name: Automatic V5 Max Build

on:
  push:
    branches:
      - wireless_playground

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli:0.2.2
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Compile Firmware
      run: |
        qmk compile -kb keychron/v5_max/ansi_encoder -km default
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: v5_max_firmware
        path: ./*.bin
