name: Automatic V5 Max Build

on:
  push:
    branches:
      - wireless_playground

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install QMK Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip git gcc-avr binutils-avr avr-libc gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi dfu-programmer dfu-util
        python3 -m pip install -r requirements.txt

    - name: Compile Firmware
      run: |
        make keychron/v5_max/ansi_encoder:default
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: v5_max_firmware
        path: .build/*.bin
