name: Automatic V5 Max Build

on:
  push:
    branches:
      - wireless_playground

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Fix Python Dependencies
      run: |
        python3 -m pip install --break-system-packages -r requirements.txt
    - name: Clean and Fix Makefile Conflict
      run: |
        make clean || true
        rm -rf .build/ || true
    - name: Compile Firmware
      run: |
        qmk compile -kb keychron/v5_max/ansi_encoder -km default
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: v5_max_firmware
        path: ./*.bin
